const ProductData = [{
        id: 0,
        name: "AAA Angus Beef Steak",
        price: 27.68,
        unit_price: "$19.77/lb",
        count: 0,
        img: "./images/products/beef.jpg",
    },
    {
        id: 1,
        name: "Fresh Strawberry",
        price: 5.97,
        unit_price: "$5.97/lb",
        count: 0,
        img: "./images/products/strawberry.jpg",
    },
    {
        id: 2,
        name: "Enriched White Bread",
        price: 1.97,
        unit_price: "29¢/100g",
        count: 0,
        img: "./images/products/bread.jpg",
    },
    {
        id: 3,
        name: "Seedless Cucumber",
        price: 1.97,
        unit_price: "Sold in singles",
        count: 0,
        img: "./images/products/cucumber.jpg",
    },
    {
        id: 4,
        name: "Organic Tomato",
        price: 0.9,
        unit_price: "Sold in singles",
        count: 4,
        img: "./images/products/tomato.jpg",
    },
    {
        id: 5,
        name: "Boneless Chicken Breast",
        price: 12.48,
        unit_price: "$1.34/100g",
        count: 0,
        img: "./images/products/chicken.jpg",
    },
    {
        id: 6,
        name: "Pepperoni Pizza",
        price: 3.97,
        unit_price: "$1.07/100g",
        count: 0,
        img: "./images/products/pizza.jpg",
    },
    {
        id: 7,
        name: "Fine-filtered 3.25% Milk",
        price: 7.28,
        unit_price: "18¢/100ml",
        count: 0,
        img: "./images/products/milk.jpg",
    },
    {
        id: 8,
        name: "Fresh Carrot",
        price: 7.41,
        unit_price: "$2.47/lb",
        count: 0,
        img: "./images/products/carrot.jpg",
    },
    {
        id: 9,
        name: "Yukon Gold potato",
        price: 5.97,
        unit_price: "$0.6/lb",
        count: 0,
        img: "./images/products/potato.jpg",
    },
    {
        id: 10,
        name: "Farms Free Run Eggs",
        price: 6.48,
        unit_price: "54¢/each",
        count: 0,
        img: "./images/products/egg.jpg",
    },
    {
        id: 11,
        name: "Lettuce Iceberg",
        price: 2.97,
        unit_price: "Sold in singles",
        count: 0,
        img: "./images/products/lettuce.jpg",
    },
    {
        id: 12,
        name: "Smoked Bacon",
        price: 4.97,
        unit_price: "$1.33/100g",
        count: 0,
        img: "./images/products/bacon.jpg",
    },
    {
        id: 13,
        name: "Macintosh Apple",
        price: 5.47,
        unit_price: "$1.82/lb",
        count: 0,
        img: "./images/products/apple.jpg",
    },
    {
        id: 14,
        name: "Garlic",
        price: 0.97,
        unit_price: "97¢/pack",
        count: 3,
        img: "./images/products/garlic.jpg",
    },
];

window.onload = () => {
    new Validators();
    const generator = new Generator();
    generator.GenerateCart();
};